[dev] Add Ruby 2.6 and 2.7 images for Oracle Linux 7 and 8
oracle/docker-images pull request #1844
Opened 2021-01-20 07:29 UTC by Djelibeybi

The Oracle Linux 7 images use Ruby from the Software Collections
Library while the Oracle Linux 8 images use the Ruby module from
the AppStream repo.

All images come with both rake and gem preinstalled.

Image sizes are really nice and small:

```
oraclelinux7-ruby:2.6   157MB
oraclelinux7-ruby:2.7   158MB
oraclelinux8-ruby:2.6   136MB
oraclelinux8-ruby:2.7   137MB
```

Note that we haven't (yet) released the `rh-ruby26` and `rh-ruby27`
SCLs for `aarch64` for Oracle Linux 7 yet, so the workflow will 
skip that combination for now. Once they're released, we 
can enable the build.

If you'd like to test the images, I've made the two packages built by my 
GitHub Action test run public:

<https://github.com/users/Djelibeybi/packages/container/package/oraclelinux7-ruby>
<https://github.com/users/Djelibeybi/packages/container/package/oraclelinux8-ruby>

This resolves #1842 because "Just Enough Image" is the goal for these base images. 
Ping @crush-157 so he can provide feedback as the original requester.

Signed-off-by: Avi Miller <avi.miller@oracle.com>

2021-01-20 07:38 UTC, mark-au commented
I'll give it a test tomorrow before I approve but you'll need a 2021 copyright date :grinning:

2021-01-20 07:46 UTC, Djelibeybi commented
> I'll give it a test tomorrow before I approve but you'll need a 2021 copyright date 😀

I have no idea what you're talking about... 😇

2021-01-20 15:59 UTC, crush-157 commented
@Djelibeybi https://github.com/users/Djelibeybi/packages/container/package/oraclelinux8-ruby takes me to 404

2021-01-20 16:01 UTC, crush-157 commented
Pulled ghcr.io/djelibeybi/oraclelinux7-ruby:2.7 to take it for a spin.

2021-01-20 19:49 UTC, Djelibeybi commented
> @Djelibeybi https://github.com/users/Djelibeybi/packages/container/package/oraclelinux8-ruby takes me to 404

This should be working now, sorry about that.

2021-01-20 22:08 UTC, Djelibeybi commented
From @crush-157 -- we need a Ruby on Rails variant as well, which requires both Node.js and yarn enabled.

2021-01-20 22:49 UTC, mark-au approved these changes
The only feedback I have is to use `${MANPATH}` in the oraclelinux7/* files for consistency but that makes no functional difference so I approve it as is

2021-01-20 22:58 UTC, cjbj commented
Any plans to include ruby-oci8 (and possibly the oracle enhanced adapter for Rails)?

2021-01-20 23:02 UTC, Djelibeybi commented
> Any plans to include ruby-oci8 (and possibly the oracle enhanced adapter for Rails)?

Can you point me towards install docs? I can add an `oci8` variant to the base Ruby image and the enhanced adapter for the Rails variant.

2021-01-20 23:18 UTC, cjbj commented
It boils down to 'gem install ruby-oci8'

See https://www.rubydoc.info/gems/ruby-oci8/file/docs/install-instant-client.md

2021-01-20 23:19 UTC, Djelibeybi commented
> It boils down to `gem install ruby-oci8`

These developer images are only allowed to install things using `yum` from `yum.oracle.com` as that's the only approval I have. :) Have we packaged this `rubygem` into an RPM that's available on `yum.oracle.com`?

2021-01-20 23:21 UTC, cjbj commented
Indeed that's the bigger question for your team :)

2021-01-20 23:23 UTC, Djelibeybi commented
> Indeed that's the bigger question for your team :)

I'm going with "no", then.

2021-01-21 07:38 UTC, Djelibeybi commented
@crush-157 you can take `ghcr.io/djelibeybi/oraclelinux7-ruby:2.7-nodejs` for a spin as a base image. You'll need to install `yarn` and then `rails`, which will require both `gcc` and `make` to be available. A sample `Dockerfile`:

```Dockerfile
FROM ghcr.io/djelibeybi/oraclelinux7-ruby:2.7-nodejs

RUN npm install -g yarn && \
    yum -y install gcc make && \
    gem install rails && \
    yum -y remove mpfr cpp kernel-headers glibc-headers glibc-devel binutils libgomp libmpc gcc make && \
    rm -rf /var/cache/yum

CMD ["rails", "--version"]
```

That gets me `Rails 6.1.1`.

2021-01-21 12:08 UTC, crush-157 commented
@Djelibeybi confirmed that Rails is installed following your incantation above.

2021-01-21 12:23 UTC, crush-157 commented
`ghcr.io/djelibeybi/oraclelinux7-ruby:2.7` doesn't seem to have `rh-ruby27-ruby-devel` installed:

```eslater:ol-ruby/ $ docker run --rm -it ghcr.io/djelibeybi/oraclelinux7-ruby:2.7 /bin/bash
bash-4.2# gem install json
Fetching json-2.5.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /opt/rh/rh-ruby27/root/usr/local/share/gems/gems/json-2.5.1/ext/json/ext/generator
/opt/rh/rh-ruby27/root/usr/bin/ruby -I /opt/rh/rh-ruby27/root/usr/share/rubygems -r ./siteconf20210121-7-jihux1.rb extconf.rb
mkmf.rb can't find header files for ruby at /opt/rh/rh-ruby27/root/usr/share/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /opt/rh/rh-ruby27/root/usr/local/share/gems/gems/json-2.5.1 for inspection.
Results logged to /opt/rh/rh-ruby27/root/usr/local/lib64/gems/ruby/json-2.5.1/gem_make.out
bash-4.2# 
```

If I build my own image from the [Dockerfile](https://github.com/Djelibeybi/docker-images/blob/add-ruby-images/OracleLinuxDevelopers/oraclelinux7/ruby/2.7/Dockerfile) then that package is there.

`make` and `gcc` also need to be installed to build native extensions.

2021-01-21 20:18 UTC, Djelibeybi commented
The updated image should (re-run `docker pull ghcr.io/djelibeybi/oraclelinux7-ruby:2.7`) but I need to add `gcc` and `make` which will increase the size of all the images.

2021-01-22 03:13 UTC, Djelibeybi commented
@crush-157 I've updated all the images over at https://github.com/Djelibeybi?tab=packages to include the right `ruby-devel` package as well as `gcc` and `make`. I think these are probably good enough for merging, but would like your final review first.

2021-01-22 09:39 UTC, crush-157 commented
Just one comment - could you please switch the `CMD` at the end to be `CMD ["irb"]` in line with the images from https://hub.docker.com/_/ruby ?

2021-01-22 15:13 UTC, Djelibeybi commented
Thanks @crush-157 I've switched the `CMD` directive as requested. Once @mark-au or @totalamateurhour give the PR a final approval I'll merge it and the images will be automatically built and published to GHCR.

2021-01-27 04:53 UTC, mark-au requested changes
`irb` is in a separate RPM named `ruby-irb` on OL8 so that needs to be included.

```
15:47 $ podman run 826 ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
15:49 $ podman run 826 
Error: container_linux.go:370: starting container process caused: exec: "irb": executable file not found in $PATH: OCI runtime command not found error
```

2021-01-27 05:28 UTC, mark-au approved these changes

2021-01-27 05:53 UTC, merged