To Deploy kubernetes pods of OracleDatabase only on nodes in a particular nodepool having label "pool"
oracle/docker-images pull request #1895
Opened 2021-04-05 06:39 UTC by Mahi0911

To Deploy Kubernetes pods of OracleDatabase only on nodes in a particular NodePool having label "pool" , Added label "pool" under nodeSelector in OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/deployment.yaml

2021-04-06 10:01 UTC, yunus-qureshi reviewed
@Mahi0911 can we generalise the label name here instead of assuming to be pool always

2021-04-06 19:43 UTC, gvenzl requested changes
As per @yunus-qureshi:
> @Mahi0911 can we generalise the label name here instead of assuming to be pool always?

2021-04-07 09:31 UTC, yunus-qureshi commented on OracleDatabase/SingleInstance/helm-charts/oracle-db/values.yaml
> +nodeLables:
@Mahi0911 plz fix this typo. nodeLables should be nodeLabels. Update all references

2021-04-07 11:11 UTC, yunus-qureshi approved these changes
Looks good for merge

2021-04-07 17:27 UTC, gvenzl approved these changes

2021-04-07 17:27 UTC, merged