ci: update build and push workflows to use GITHUB_TOKEN
oracle/docker-images pull request #1907
Opened 2021-04-21 00:09 UTC by Djelibeybi

This provides extra security by not requiring repository or org
level secrets. Includes tweaking the individual builds to still
publish to the Oracle namespace. This required updating the
permissions for each package to allow this repo to push.

Signed-off-by: Avi Miller <avi.miller@oracle.com>

2021-04-21 00:10 UTC, Djelibeybi commented
I have tested this on a (short-lived) branch of this repo. You can see the images were actually updated recently by me.

2021-04-21 02:03 UTC, cjbj approved these changes

2021-04-21 07:59 UTC, AmedeeBulle requested changes

2021-04-21 07:59 UTC, AmedeeBulle commented on .github/workflows/build-and-push-instantclient-images.yml
> +              docker build --tag ghcr.io/${{ github.repository_owner }}/${o}-instantclient:${i} OracleInstantClient/${o}/${i}
The `<OWNER>` in the repository URL must be lowercase, and `github.repository_owner` is case sensitive...

2021-04-21 07:59 UTC, AmedeeBulle commented on .github/workflows/build-and-push-instantclient-images.yml
> +              docker push ghcr.io/${{ github.repository_owner }}/${o}-instantclient:${i}
Lowercase repo owner

2021-04-21 07:59 UTC, AmedeeBulle commented on .github/workflows/build-and-push-nosql-image.yml
> +          docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$TAG
Lowercase repo owner

2021-04-21 22:21 UTC, Djelibeybi commented
I've lowercased the GitHub repository owner field. Tested and working on my fork.

2021-04-22 10:03 UTC, AmedeeBulle approved these changes
LGTM

2021-04-22 10:03 UTC, merged