Added Sharding extension in Single Instance Docker Image
oracle/docker-images pull request #2004
Opened 2021-07-06 03:39 UTC by psaini79

Added Sharding Script as an extension in SIDB.

2021-07-06 06:29 UTC, yunus-qureshi commented on OracleDatabase/SingleInstance/extensions/sharding/runOracle.sh
> +# Author: Paramdeep.saini@oracle.com
Please check the copyright. Should it be 2021 as Since says Mar, 2021?

2021-07-06 06:30 UTC, yunus-qureshi approved these changes

2021-07-08 19:14 UTC, gvenzl requested changes
Comments provided per email.

2021-07-14 12:06 UTC, yunus-qureshi commented
Closing this as we @abhisbyk PR on the sharding extension

2021-07-14 12:06 UTC, closed without merging