21c Docker image support
oracle/docker-images pull request #2057
Opened 2021-08-14 17:04 UTC by marcelo-ochoa

This PR is for building latest Oracle EE and SE2 Docker image for RDBMS version 21c, using latest download: https://www.oracle.com/database/technologies/oracle-database-software-downloads.html
It is basically a clone of 19c scripts tested on Ubuntu 20.04 and Docker version 20.10.8
Note: There is no oracle-database-preinstall-19c rpm file at Oracle Linux 7 slim images, but it seem to work fine preparing the environment and dependency for 21c version.

2021-08-16 14:02 UTC, abhisbyk commented
Raised the PR #2058  for supporting 21c Single Instance Database container image creation. It contains some additional things as compared to 19c. Please review.
@gvenzl

2021-08-17 07:30 UTC, Djelibeybi requested changes

2021-08-17 07:30 UTC, Djelibeybi commented on OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile
> +FROM oraclelinux:8-slim as base
Please do not use `oraclelinux:8-slim`, as per the base image rules in the contribution guide: https://github.com/oracle/docker-images/blob/main/CONTRIBUTING.md#base-image-rules

2021-08-17 07:31 UTC, Djelibeybi requested changes

2021-08-17 07:31 UTC, Djelibeybi commented on OracleDatabase/SingleInstance/dockerfiles/21.3.0/setupLinuxEnv.sh
> +microdnf -y install oracle-database-preinstall-21c openssl && \
After switching to `oraclelinux:8`, change this to `dnf` please.

2021-08-17 07:32 UTC, Djelibeybi commented on OracleDatabase/SingleInstance/dockerfiles/21.3.0/setupLinuxEnv.sh
> +rm -rf /var/cache/yum && \
This should be changed to `rm -rf /var/cache/dnf`

2021-08-18 00:17 UTC, gvenzl commented
I believe this PR can be closed in favor of the already merged PR #2058. @abhisbyk, can you confirm once again, please?

2021-08-18 03:26 UTC, abhisbyk commented
@gvenzl 
Yes, this PR can be closed

2021-08-19 14:24 UTC, closed without merging