First release of Oracle GoldenGate Veridata docker scripts
oracle/docker-images pull request #2115
Opened 2021-10-04 22:31 UTC by arnabnandioracle

Initial commit

Signed-off-by: Arnab Nandi <arnab.x.nandi@oracle.com>

2021-10-04 23:21 UTC, Djelibeybi requested changes
There are lots of changes necessary to meet the requirements for this repo.  I stopped reviewing after 70 comments. Please review the rest of the files I skipped and make the same fixes to those.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +Download the latest bundle patch.
From where? How? Where should I put it?

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +5) Run buildDockerImage.sh
Needs to be changed to `buildContainerImage.sh` and formatted as a heading

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +Usage: buildDockerImage.sh -v [version]
Change to `buildContainerImage.sh` and the entire output needs to be formatted as a code sample.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +Builds a Docker Image for Oracle GoldenGate Veridata.
Change to `Builds a container image for Oracle GoldenGate Veridata.`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +How to run OGG Veridata Server
Needs to be formatted as a heading

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +1) Create Docker Bridge
Needs to be formatted as heading. Also, you're not creating a bridge, you're creating a _network_ of type `bridge` so this should be "Create Docker network".

Also, you should explain why this network is necessary. What's the purpose of it?

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +e.g.
Remove this line.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +docker network create -d bridge VdtBridge
Format as a code sample

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +2) Oracle Database
Format as a heading

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +Make sure the Database is running on the network ,created earlier, using --network.
Make sure what database is running on which network? You provided example commands before, why are they missing for this step? How does the user connect to an external Database that's not running as a container or even on this host?

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +3) OGG Veridata Admin Server
Format this as a heading

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +Edit vdt.env file and execute run_admin_server.sh.
The filenames should be wrapped in back ticks as they are literals. Also, you must explain what needs to be edited and why and where to run the script. And what that script does. And how to run the image without a script.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +Edit vdt.env file and execute run_managed_server.sh.
Are these the same edits as the previous step? Do I change my edits? How many copies of this file exist?

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +4) OGG Veridata Managed Server
Format as a heading

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +
Remove all the blank lines

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +5) OGG Veridata Agent
Format as a heading

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +Edit vdtagent.env and execute run_agent.sh.
Same as previous. Formatting and context are missing.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +# Copyright (c) 2020-2021 Oracle and/or its affiliates. All rights reserved.
Remove "All rights reserved" as Oracle no longer uses this phrase.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
Change the URL to use `https://`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +#!/bin/bash
This file needs to be renamed to `buildContainerImage.sh`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +Usage: buildDockerImage.sh -v [version]
change to `buildContainerImage.sh`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +Builds a Docker Image for Oracle GoldenGate Veridata.
Change `Docker Image` to `container image`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +   -f: FMW Release version . Default is 12.2.1.4-210701
remove the space before the `.`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +Copyright (c) 2020-2021 Oracle and/or its affiliates. All rights reserved.
Remove "All rights reserved"

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
Change the URL to `https://`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +  Oracle GoldenGate Veridata Docker Image for version: $VERSION.
Change `Docker Image` to `container image`

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/buildDockerImage.sh
> +  echo "Oracle GoldenGate Veridata Docker Image was NOT successfully created. Check the output and correct any reported problems with the docker build operation."
Change `Docker Image` to `container image` and remove the word `docker`.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/applyRollbackPatch.sh
> +# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
Remove the phrase "All rights reserved"

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtAgent.sh
> +# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
Remove "All rights reserved"

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
Remove "All rights reserved"

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +#echo "VERIDATA_PASSWORD=${VERIDATA_PASSWORD:?"Please set VERIDATA_PASSWORD"}"
Remove this line

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +#echo "DATABASE_PASSWORD=${DATABASE_PASSWORD:?"Please set DATABASE_PASSWORD"}"
Remove this line

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +#echo "DATABASE_JDBC_URL=${DATABASE_JDBC_URL} "
Remove this line

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +    #JDBC_URL="jdbc:oracle:thin:@$CONNECTION_STRING"
Remove this line

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +#CONNECTION_STRING="${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SERVICE}"
Remove this line and the next one

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +#CONFIGURE_DOMAIN="true"
Remove this line and the next one

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +      echo "username=${VERIDATA_USER}" >> ${DOMAIN_HOME}/servers/${ADMIN_NAME}/security/boot.properties
This is not an acceptable way to store user credentials.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +      echo "password=${VERIDATA_PASSWORD}" >> ${DOMAIN_HOME}/servers/${ADMIN_NAME}/security/boot.properties
This is not an acceptable method of storing user credentials

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +      echo "$ORACLE_HOME/oracle_common/common/bin/wlst.sh -skipWLSModuleScanning $ORACLE_HOME/container-scripts/createVeridataDomain.py -oh $ORACLE_HOME -jh $JAVA_HOME -dh $DOMAIN_HOME -name $VERIDAT
Why are you `echo`'ing this?

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +echo "Java Options: ${JAVA_OPTIONS}"
Why are you `echo`'ing this?

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createOrStartVdtDomain.sh
> +#touch ${DOMAIN_HOME}/servers/${ADMIN_NAME}/logs/${ADMIN_NAME}.log
Remove this line.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createVeridataDomain.py
> +#
You're missing a shebang line. All scripts must have the interpreter defined on the first line.

2021-10-04 23:21 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/container-scripts/createVeridataDomain.py
> +# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
Remove "All rights reserved"

2021-10-04 23:22 UTC, Djelibeybi commented
You need to remove all commented out lines, all debugging lines, most references to Docker (except when used as a specific example) and make sure all your Markdown files are formatted correctly. This is considered Oracle documentation so it should be at least reviewed by your doc team for adherence to all doc standards.

2021-11-13 19:29 UTC, Djelibeybi requested changes

2021-11-13 19:29 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/LICENSE.txt
> +Copyright (c) 2021 Oracle and/or its affiliates.  All rights reserved.
Please remove this file from your pull request.

2021-11-13 19:29 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/run_admin_server.sh
> +extract_env ADMIN_CONTAINER_NAME ${scriptDir}/vdt.env
Do you need to run this three times?

2021-11-13 19:29 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/run_admin_server.sh
> +#extract_env DOMAIN_HOST_VOLUME ${scriptDir}/vdt.env
If you don't need this line, remove it.

2021-11-13 19:29 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
>  `buildDockerImage.sh -v 12.2.1.4-210630 -i fmw_12.2.1.4.0_ogg_Disk1_1of1.zip -p p32761281_122140_Generic.zip`
You need to change the example to `buildContainerImage.sh`

2021-11-15 19:12 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/README.md
> +https://www.oracle.com/middleware/technologies/goldengate-downloads.html
The instruction is verified from our Documentation Team.

2021-11-15 19:15 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/buildContainerImage.sh
> +docker build --build-arg VERIDATA_VERSION=${VERIDATA_VERSION} --build-arg INSTALLER_VERSION=${INSTALLER_VERSION} --build-arg INSTALLER=${VDT_INSTALLER} --build-arg FMW_VERSION=${FMW_VERSION} --build-
Adhering to the existing release of Oracle FMW Infrastructure. Please follow the section "Build the FMW Infrastructure Image" in the link

https://github.com/oracle/docker-images/tree/main/OracleFMWInfrastructure/dockerfiles/12.2.1.4

2021-11-15 19:18 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/README.md
> +This Docker configuration has been used to create the Oracle GoldenGate Veridata image. The README facilitates the configuration and environment set up for DevOps users. This project includes the cre
Read the heading section of "Oracle FMW Infrastructure" spinet pasted here :

"
This Docker configuration has been used to create the Oracle Fusion Middleware Infrastructure image. Providing this FMW image facilitates the configuration and environment set up for DevOps users. This project includes the creation of an FMW Infrastructure domain.

The certification of the Oracle FMW Infrastructure on Docker does not require the use of any file presented in this repository. Customers and users are welcome to use them as starters, and customize, tweak, or create from scratch, new scripts and Dockerfiles.
"

https://github.com/oracle/docker-images/tree/main/OracleFMWInfrastructure/dockerfiles/12.2.1.4

Adhering to existing standard. Please be informed that README.md has gone through our Documentation team.

2021-11-15 19:18 UTC, Djelibeybi commented on OracleVeridata/12.2.1.4/README.md
> +https://www.oracle.com/middleware/technologies/goldengate-downloads.html
What instruction? There is no instruction.

2021-11-15 19:21 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/README.md
> +https://www.oracle.com/middleware/technologies/goldengate-downloads.html
The latest file looks like this 
"
3. Oracle GoldenGate Veridata Installer:

Download the Oracle GoldenGate Veridata 12.2.1.4.0 Installer in to your local directory from the following location:

https://www.oracle.com/middleware/technologies/goldengate-downloads.html

"

2021-11-15 19:45 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/LICENSE.txt
> +Copyright (c) 2021 Oracle and/or its affiliates.  All rights reserved.
Removed

2021-11-15 19:46 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/README.md
> +Create Docker network to run Admin, Managed server, and repository Database (in case needed).
Fixed

2021-11-15 19:47 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/README.md
> +To build an Oracle Database image run the following command:
Fixed

2021-11-15 19:47 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/README.md
>  `buildDockerImage.sh -v 12.2.1.4-210630 -i fmw_12.2.1.4.0_ogg_Disk1_1of1.zip -p p32761281_122140_Generic.zip`
Fixed

2021-11-15 19:47 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/run_admin_server.sh
> +#extract_env DOMAIN_HOST_VOLUME ${scriptDir}/vdt.env
Merge issues fixed

2021-11-15 19:47 UTC, arnabnandioracle commented on OracleVeridata/12.2.1.4/run_admin_server.sh
> +extract_env ADMIN_CONTAINER_NAME ${scriptDir}/vdt.env
Merge issue fixed

2021-11-15 20:24 UTC, Djelibeybi approved these changes

2021-11-15 20:25 UTC, Djelibeybi approved these changes

2021-11-15 20:26 UTC, merged