updated versions to the Jan 2022 CPU releases
oracle/docker-images pull request #2231
Opened 2022-01-18 18:28 UTC by aureliogrb

Signed-off-by: Aurelio Garcia-Ribeyro <aurelio.garciaribeyro@oracle.com>

2022-01-18 19:15 UTC, rjeberhard approved these changes

2022-01-18 19:16 UTC, rjeberhard requested changes
I accidentally approved prior to looking at the copyright statements... These need to be updated for 2022.

2022-01-18 21:50 UTC, Djelibeybi requested changes
Yep, what @rjeberhard said: please update the copyright headers to `2019, 2022` and remove `All rights reserved.` while you're there. :)

2022-01-20 00:08 UTC, aureliogrb commented
Updated the copyright years as requested.

2022-01-20 00:12 UTC, rjeberhard approved these changes

2022-01-20 02:27 UTC, Djelibeybi approved these changes

2022-01-20 02:27 UTC, merged