optimize SOA image size and doc corrections
oracle/docker-images pull request #2249
Opened 2022-02-11 06:10 UTC by sbattagi

This PR contains the SOA Dockerfile fixes to optimize the image size.

Signed-off-by: Sambasiva Battagiri <sambasiva.battagiri@oracle.com>

2022-02-11 10:28 UTC, vivek-sam submitted a review, later dismissed
Reviewed the code and it is in line with the internal Repo.

2022-02-15 06:00 UTC, rdas0405 approved these changes

2022-02-18 11:17 UTC, sbattagi commented
Kindly merge this transaction.

2022-02-24 14:46 UTC, sbattagi commented
@rjeberhard   Could you please merge this transaction? This fix is required for latest SOA release.

2022-03-01 16:06 UTC, rjeberhard requested changes

2022-03-01 20:33 UTC, Djelibeybi requested changes

2022-03-01 20:33 UTC, Djelibeybi commented on OracleSOASuite/dockerfiles/12.2.1.4/Dockerfile
> +RUN if ls /u01/oracle/cfgtoollogs/opatch/*.log; then \
Agreed, please combine these `RUN` directives into a single one.

2022-03-02 13:15 UTC, sbattagi commented on OracleSOASuite/dockerfiles/12.2.1.4/Dockerfile
> +RUN if ls /u01/oracle/cfgtoollogs/opatch/*.log; then \
Merged the run commands and committed the changes. Please review.

2022-03-02 13:23 UTC, rjeberhard approved these changes

2022-03-02 21:16 UTC, Djelibeybi approved these changes

2022-03-02 21:16 UTC, Djelibeybi commented
Still waiting on approval from @rdas0405 whos is the code owner for this.

2022-03-07 05:29 UTC, rdas0405 approved these changes

2022-03-07 15:06 UTC, merged