setPassword script condition for prebuiltdb extended image
oracle/docker-images pull request #2278
Opened 2022-03-24 12:34 UTC by abhisbyk

If `ORACLE_PWD` is passed in `docker run` command while running the database container image extended with **prebuiltdb** extension, don't allow user to change the password using `setPassword.sh` script. As the password is in the environment and if the container is restarted, then the changed password will not persist. The password will revert back to the one which exists in the environment.

Signed-off-by: abhisbyk <abhishek.by.kumar@oracle.com>

2022-03-24 16:35 UTC, gvenzl requested changes

2022-03-25 06:13 UTC, abhisbyk commented on OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh
> +      echo "Unable to change the password for prebuiltdb. The password is already there in the environment. Exiting..."
Right, it will better work as warning. Changed the language of the warning according to your suggestions.
Thanks

2022-03-25 10:46 UTC, yunus-qureshi submitted a review, later dismissed

2022-03-25 18:13 UTC, gvenzl commented on OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh
> +      echo "Unable to change the password for prebuiltdb. The password is already there in the environment. Exiting..."
Looks much better, thank you for that! Is the space between `ignored !` intentional?

2022-03-25 19:56 UTC, gvenzl commented on OracleDatabase/SingleInstance/dockerfiles/21.3.0/setPassword.sh
> +      echo "Unable to change the password for prebuiltdb. The password is already there in the environment. Exiting..."
No worries, that's why a second pair of eyes is always a good thing :)

2022-03-25 19:56 UTC, gvenzl approved these changes

2022-03-25 19:57 UTC, merged