Changes after testing MySQL and PostgreSQL for docker
oracle/docker-images pull request #2351
Opened 2022-04-25 11:49 UTC by jiteshtiwari

docker commands are updated for MySQL and PostgreSQL.

    The copyright year is also updated.

2022-04-25 12:46 UTC, sbalousek requested changes

2022-04-25 12:46 UTC, sbalousek commented on OracleGoldenGate/21c/README.md
> +The container image name for individual database is different. Use the below image name with `docker run` command to create and start a container from the Oracle GoldenGate container image.
This needs re-work.

Just leave the 'Use the `docker run`...' line alone and use `<image-name>` on line 95, which you already have. Then add `<image-name>` to that list of parameters. with a brief description. Do *not* reference the database name, but instead use:

```md
* `<image-name>`    - The name of the previously created container image
```

2022-04-25 12:46 UTC, sbalousek commented on OracleGoldenGate/21c/README.md
> +    <image name>
Do not change. This is a fixed example.

2022-04-25 12:46 UTC, sbalousek commented on OracleGoldenGate/21c/README.md
> +$ docker run <image name>
Do not change. This is a fixed example.

2022-04-25 12:58 UTC, sbalousek commented on OracleGoldenGate/21c/README.md
> +$ docker build --tag=oracle/goldengate-for-PostgreSQL:21.3.0.0.0 \
Instead of all these examples, it would be cleaner to have *one* example with the `zip` file name as a parameter.

2022-04-25 21:45 UTC, sbalousek approved these changes

2022-05-02 23:58 UTC, Djelibeybi commented
A reminder to assign me to a PR so I'm notified when it's ready to merge.

2022-05-02 23:59 UTC, merged