Update the no sql image
oracle/docker-images pull request #2398
Opened 2022-06-17 10:23 UTC by dario-vega

This PR updates the Oracle NoSQL Dockerfile to align with the latest version and bundles.
    this GitHub download now the latest version kv-ce-21.2.46.zip.
This PR updates with some improvements to the Oracle NoSQL CE image.
    fixes #2365 - The CE 21.2 version introduces a new parameter storagedirsizegb

Signed-off-by: Dario Vega dario.vega@oracle.com

2022-06-17 12:12 UTC, mikebrey approved these changes

2022-06-21 19:11 UTC, Djelibeybi requested changes

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +replication and no administration. It runs in a single process. **Note:** KVLite is not intended for production deployment or performance measurements.
```suggestion
This container image uses a simplified version of the Oracle NoSQL Database called KVLite. KVLite runs as a single process that provides a single storage node and single storage shard. KVLite does not include replication or administration. 

> **Note:** KVLite is not intended for production deployment or performance measurements.
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +The value of N is in GB and must be >= 1
```suggestion
The value of `N` is in gigabytes and must be greater than 1GB.
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +The value of N is in GB and must be >= 1
```suggestion
The value of `N` is in gigabytes and must be greater than 1GB.
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +Note the required use of --link for proper hostname check (actual KVLite container is named kvlite; alias is store).
```suggestion
Note the required use of `--link` for proper hostname check (actual KVLite container is named `kvlite` and its alias is `store`).
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +Note: -host must be the same name used when starting the container
```suggestion
Note: the value provided for `-host` must match the name used when starting the container.
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +You will use you current HOSTNAME as a value for the --hostname
```suggestion
Use the environment variable `$HOSTNAME` as the value for the `--hostname`
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +In this case, You need to publish all internal ports and the KV_PROXY_PORT.
```suggestion
In this case, You need to publish all internal ports and the `KV_PROXY_PORT`:
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +- 8080 KV_PROXY_PORT
```suggestion

- 5000 `KVPORT`
- 5010-5020 `KV_HA_RANGE` 
- 5021-5049 `KV_SERVICE_RANGE`
- 8080 `KV_PROXY_PORT`
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +It allows starting the container without publishing all internal ports (KVPORT, KV_HARANGE, KV_SERVICERANGE) but only the KV_PROXY_PORT.
```suggestion
**Note**: We recommend running NoSQL Command-Line and creating a container-to-container connection as detailed above.. 

It allows you to start a container with only the `KV_PROXY_PORT` enabled. 
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +If you want to run the NoSQL command to ping the kvlite store from another container:
```suggestion
If you want to run the NoSQL command to ping the KVLite store from another container:
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +If you want to run without --link, you cannot use any alias when starting the container (use HOSTNAME).
```suggestion
If you want to run without `--link`, you can not use any alias when starting the container, so use `$HOSTNAME` instead..  
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +The value of N is in GB and must be >= 1
```suggestion
The value of `N` is in gigabytes and must be greater than 1GB.
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
>  Note: -host must be the same name used when starting the container
```suggestion
Note: `-host` must be the same name used when starting the container
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +please review the [product documentation](https://docs.oracle.com/en/database/other-databases/nosql-database/index.html).
```suggestion
please review the [Oracle NoSQL Database product documentation](https://docs.oracle.com/en/database/other-databases/nosql-database/index.html).
```

2022-06-21 19:11 UTC, Djelibeybi commented on NoSQL/README.md
> +Oracle NoSQL Community Edition is licensed under the [APACHE LICENSE v2.0](https://docs.oracle.com/en/database/other-databases/nosql-database/22.1/license/index.html#NSXLI-GUID-006E432E-1965-45A2-AED
```suggestion
Oracle NoSQL Community Edition is released under the [Apache 2.0 License](https://docs.oracle.com/en/database/other-databases/nosql-database/22.1/license/index.html#NSXLI-GUID-006E432E-1965-45A2-AEDE-204BD05E1560) . 
```

2022-06-21 23:48 UTC, mikebrey submitted a review, later dismissed
changes all look reasonable

2022-06-22 21:03 UTC, Djelibeybi submitted a review, later dismissed

2022-06-23 07:42 UTC, Djelibeybi approved these changes

2022-06-23 12:06 UTC, mikebrey approved these changes
approved

2022-06-23 12:40 UTC, merged