add warning
oracle/docker-images pull request #2432
Opened 2022-08-18 21:16 UTC by rosemarymarano

Added warning about creating WebLogic images.

2022-08-18 21:18 UTC, ddsharpe submitted a review, later dismissed

2022-08-18 22:39 UTC, mriccell requested changes
We need this notice also in the README of the [OracleFMWInfrastructure](https://github.com/mriccell/docker-images/tree/main/OracleFMWInfrastructure)

2022-08-18 22:39 UTC, mriccell commented on OracleWebLogic/README.md
> +**IMPORTANT**: The samples in this repository are for advanced use cases only. We provide Dockerfiles as samples to build WebLogic images but this is _NOT_ a recommended practice. We suggest alternat
Lets add we recommend obtaining patched WebLogic Server images, these images are patched with the latest security patches.

2022-08-19 13:24 UTC, mriccell approved these changes

2022-08-19 13:24 UTC, merged