Added fix for handling systemd failure inside the container
oracle/docker-images pull request #2636
Opened 2023-05-15 17:37 UTC by psaini79

2023-05-16 05:42 UTC, Djelibeybi requested changes
Please resolve the linter issues instead of disabling the checks at the file level. We've already modified the linter to only block on actual warnings and errors so everything it reports needs to be resolved.

2023-05-16 05:42 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/19.3.0/AddNode.sh
> +# shellcheck disable=SC2181,SC2016,SC1091,SC2086
None of these should be disabled as they're all pretty straightforward to fix. Please fix the actual issues instead of suppressing them.

2023-05-16 07:43 UTC, psaini79 commented
I made the changes as per your suggestion. Please review.

2023-05-16 08:41 UTC, Djelibeybi commented
There is an icon next to my name under "Reviewers" of a circle made up of two arrows. In future, click that to request a new review.

2023-05-16 08:46 UTC, Djelibeybi requested changes

2023-05-16 08:46 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/19.3.0/setupGridEnv.sh
> +#local disk_name
Remove these lines if they are no longer required.

2023-05-16 08:46 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/19.3.0/setupGridEnv.sh
> +#local disk_name
Remove these lines if they are no longer required.

2023-05-16 08:46 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/21.3.0/setupGridEnv.sh
> +#local disk_name
Remove these lines if they are no longer required.

2023-05-16 08:46 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/21.3.0/setupGridEnv.sh
> +#local temp_str
Remove this line if it is not required.

2023-05-18 08:55 UTC, Djelibeybi approved these changes

2023-05-18 08:55 UTC, merged