common scripts added
oracle/docker-images pull request #2776
Opened 2024-03-27 10:01 UTC by saurabhuja

2024-03-27 18:21 UTC, Djelibeybi requested changes
The copyright lines need to be fixed and the Python shebang lines need to use versioned Python.

2024-03-27 18:21 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/common/scripts/cmdExec
> +# Copyright (c) 2018-2024 Oracle and/or its affiliates. All rights reserved.
Please change all copyright lines for _new_ files to:

`Copyright (c) 2024, Oracle and/or its affiliates.`

2024-03-27 18:21 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/common/scripts/cmdExec
> +# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
Please change all instances of this URL to use `https` instead of `http`.

2024-03-27 18:21 UTC, Djelibeybi commented on OracleDatabase/RAC/OracleRealApplicationClusters/common/scripts/main.py
> +#!/usr/bin/python
It's bad practice to use unversioned Python. Please change all instances to `python3`.

2024-03-28 03:43 UTC, saurabhuja commented
Thank you @Djelibeybi

2024-03-28 04:03 UTC, Djelibeybi approved these changes

2024-03-28 04:03 UTC, Djelibeybi commented
Still needs to be approved by @psaini79 as code owner before I can merge.

2024-03-28 05:41 UTC, psaini79 approved these changes

2024-03-28 05:42 UTC, merged