Update SECURITY.md
oracle/docker-images pull request #2800
Opened 2024-05-10 14:37 UTC by LesiaChaban

Fixing minor rendering issue in SECURITY.md .

2024-05-10 15:37 UTC, Djelibeybi commented
Instead of removing the link, it should be fixed to point to https://www.oracle.com/au/security-alerts/ instead.

2024-05-10 19:40 UTC, Djelibeybi requested changes

2024-05-10 19:40 UTC, Djelibeybi commented on SECURITY.md
> +Oracle Critical Patch Update program. Additional
```suggestion
[Oracle Critical Patch Update][4] program. Additional
```

Then change `[security alerts][4]` to `[security alerts][5]` and modify the links at the bottom of the file accordingly:

```markdown
[4]: https://www.oracle.com/security-alerts/#CriticalPatchUpdates
[5]: https://www.oracle.com/au/security-alerts/#SecurityAlerts
```

2024-05-14 00:24 UTC, gvenzl approved these changes

2024-05-14 10:37 UTC, Djelibeybi approved these changes

2024-05-14 10:37 UTC, merged