Instant Client 23ai containers
oracle/docker-images pull request #2824
Opened 2024-06-28 07:21 UTC by cjbj

Initial Instant Client 23ai container push

2024-06-28 10:30 UTC, Djelibeybi requested changes
The `FROM` directive in the OL9 Dockerfile has a typo. :)

2024-06-28 10:30 UTC, Djelibeybi commented on OracleInstantClient/oraclelinux9/23/Dockerfile
> +FROM oraclelinux:8
This should be `FROM oraclelinux:9`

2024-06-29 06:26 UTC, cjbj commented on OracleInstantClient/oraclelinux9/23/Dockerfile
> +FROM oraclelinux:8
Fixed; thanks.

2024-07-01 02:40 UTC, Djelibeybi approved these changes

2024-07-01 02:42 UTC, Djelibeybi commented
@AmedeeBulle can you take a look at the linter errors for the GitHub Action? I'm going to merge this in the meantime.

2024-07-01 02:42 UTC, merged